language: rust
    
env:
    global:
        - LD_LIBRARY_PATH: /usr/local/lib

before_install:
    - uname -a
    - lsb_release -a
    - sudo apt-add-repository --yes ppa:zoogie/sdl2-snapshots       # libsdl2

install:
    - sudo apt-get install -y libsdl2-dev 
    - sudo apt-get install -y libsdl2-gfx-dev
    - sudo apt-get install -y libsdl2-image-dev
    - sudo apt-get install -y libsdl2-mixer-dev 
    - sudo apt-get install -y libsdl2-ttf-dev
