language: rust
sudo: required
dist: trusty

env:
    global:
        - LD_LIBRARY_PATH: /usr/local/lib

before_install:
    - uname -a
    - lsb_release -a

install:
    - sudo apt-get install --yes libsdl2 
    - sudo apt-get install --yes libsdl2-gfx
    - sudo apt-get install --yes libsdl2-image
    - sudo apt-get install --yes libsdl2-mixer 
    - sudo apt-get install --yes libsdl2-ttf
