language: rust
sudo: required
dist: trusty

env:
    global:
        - LD_LIBRARY_PATH: /usr/local/lib

before_install:
    - uname -a
    - lsb_release -a

install:
    - sudo apt-get install --yes libsdl2-dev 
    - sudo apt-get install --yes libsdl2-gfx-dev
    - sudo apt-get install --yes libsdl2-image-dev
    - sudo apt-get install --yes libsdl2-mixer-dev
    - sudo apt-get install --yes libsdl2-ttf-dev
