[package]
name = "pong"
description = "A Pong clone written in Rust"
version = "0.0.1"
license = "MIT"
authors = ["wickus.martin <wickus.martin@gmail.com>"]
keywords = ["pong"]

[[bin]]
name = "pong"
path = "src/main.rs"

[dependencies]
glium = "0.10.0"
rand = "0.3.8"
clock_ticks = "0.0.6"
